version: 2.1

commands:
  checkout-repository:
    description: Checkout this repository and its submodules
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
  export-cxx-dev-tools:
    description: Add cxx dev tools to PATH
    steps:
      - run:
          name: Add cxx dev tools to PATH
          command: |
            . export.sh
            echo 'export PATH='$PATH >> $BASH_ENV
            echo 'export CXX_DEV_TOOLS_PATH='$CXX_DEV_TOOLS_PATH >> $BASH_ENV
  run-cmake-lint:
    description: Run cmake lint
    steps:
      - run:
          name: Run cmake lint
          command: run-cmake-lint.sh "$(< .cmake-format-files)"
  test-cmake-format:
    description: Run cmake-format tests
    steps:
    - run:
        name: Run cmake-format tests
        command: test/cmake-format/run-tests.sh
  test-clang-format:
    description: Run clang-format tests
    steps:
    - run:
        name: Run clang-format tests
        command: test/clang-format/run-tests.sh


jobs:
  lint:
    docker:
      - image: tschaffter/cxx-ci
    steps:
      - checkout-repository
      - export-cxx-dev-tools
      - run-cmake-lint
  test:
    docker:
      - image: tschaffter/cxx-ci
    steps:
      - checkout-repository
      - export-cxx-dev-tools
      - test-cmake-format
      - test-clang-format


workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - develop
                - /rc-.*/
      - lint:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
                - /rc-.*/
