version: 2.1

commands:
  checkout-repository:
    description: Checkout this repository and its submodules
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
  export-cxx-dev-tools:
    description: Add cxx dev tools to PATH
    steps:
      - run:
          name: Add cxx dev tools to PATH
          command: |
            . export.sh
            echo 'export PATH='$PATH >> $BASH_ENV
            echo 'export CXX_DEV_TOOLS_PATH='$CXX_DEV_TOOLS_PATH >> $BASH_ENV
  run-cmake-lint:
    description: Run cmake lint
    steps:
      - run: run-cmake-lint.sh "$(< .cmake-format-files)"
  # run-clang-lint:
  #   description: Run clang lint
  #   steps:
  #     - run: ./tools/clang/run-clang-format-check.sh


jobs:
  lint:
    docker:
      - image: tschaffter/cxx-ci
    steps:
      - checkout-repository
      - export-cxx-dev-tools
      - run-cmake-lint
      # - run-clang-lint


workflows:
  version: 2
  test:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - master
                - develop
                - /rc-.*/
